import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import request from '../utils/request'
import Results from '../components/Results'

export default function Home({results}) {
  //console.log(props);
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Navbar/>
      <Results results={results}/>
    </div>
  )
}


export async function getServerSideProps(context){
 const genre = context.query.genre;
  console.log(genre)
  const req = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`).then((res)=>
    res.json()
  )
  return {
    props:{
      results:req.results
    }
  }
}
